### PR TITLE
Merge request from refactoring_2

### PR DESCRIPTION
**Pull request by gioiannu**

### CODE REVIEW

**Review by aleff-github — APPROVED** [review]
Approved

**Review by pierpaolosestito-dev — APPROVED** [review]
No comment and request changes about this pull request.

**Review by AleandroPresta — APPROVED** [review]
Changes approved.

**Review by salvatoreadduci — APPROVED** [review]
I approve changes

**Review by GabrielTripodi — APPROVED** [review]
I found no errors. I approve.

**Review by FrancescaMurano — APPROVED** [review]
No Error. Approved!

**Pull request merged**
