### PR TITLE
Parser2

### PR DESCRIPTION
**Pull request by AleandroPresta**

### CODE REVIEW

**Review by aleff-github — APPROVED** [review]
Approved

**Review by pierpaolosestito-dev — APPROVED** [review]
No comment or request changes. Approved.

**Review by GabrielTripodi — APPROVED** [review]
I found no errors. I approve

**Review by FrancescaMurano — APPROVED** [review]
Review is ok

**Review by salvatoreadduci — APPROVED** [review]
I approve changes

**Review by gioiannu — APPROVED** [review]
Ok, approved

**Pull request merged**
